### ISSUE TITLE
create multi-resolution meshes

### ISSUE THREAD

**Issue by spikeliu** [seung-lab/igneous#103]
Is there a way to create multi-resolution meshes using igneous? The instructions on README.md seems to generate legacy single resolution meshes only.

**Comment by william-silversmith** [comment]
This is a feature I'm working on but it's not ready yet. I think nyroglancer has some capability for this right now: https://github.com/seung-lab/cloud-volume/pull/477

**Comment by davidackerman** [comment]
In case it is useful, I also worked on creating multi-resolution meshes: https://github.com/janelia-cosem/multiresolution-mesh-creator. The code assumes you already either:
1. Have meshes at a single high resolution, in which case it will downsample them as desired to create the lower resolution versions, or
2. Have individual meshes at all the desired scales, in which case it will skip creation of the downsampled versions.

It then combines the multi-scale meshes, chunking them appropriately and slicing them to ensure they are divisible by 2x2x2 subregions. It then outputs the resulting meshes in the [multi-resolution neuroglancer format](https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/meshes.md#multi-resolution-mesh-format).

**Comment by davidackerman** [comment]
Yeah I only had to slightly modify the existing Cython wrapper for draco (from the original [dvidutils repo](https://github.com/stuarteberg/dvidutils)), with the quantizer added in [my fork](https://github.com/davidackerman/dvidutils).

Previously, I was generating multiresolution meshes starting with the highest resolution n5 file (so lod 0). The code I was using, based on a modified version of code from [flyemflows](https://github.com/janelia-flyem/flyemflows), would then downsample the n5 to the relevant lods. I set the downsampling to not use 0 in a downsampled region if any object id was present in the downsampled region (rather than simple majority vote). This prevented thin objects from being fragmented, but leads to "thicker" meshes. The results can be seen here, for example [here](https://neuroglancer-demo.appspot.com/#!%7B%22dimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%2C%22position%22:%5B24800.5%2C2209.58642578125%2C21113.19140625%5D%2C%22crossSectionOrientation%22:%5B1%2C0%2C0%2C0%5D%2C%22crossSectionScale%22:8.1827068401352%2C%22projectionOrientation%22:%5B0.9163970351219177%2C-0.0037566586397588253%2C0.29053857922554016%2C0.2752993404865265%5D%2C%22projectionScale%22:41997.05975405403%2C%22layers%22:%5B%7B%22type%22:%22segmentation%22%2C%22source%22:%5B%22n5://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-3/jrc_hela-3.n5/labels/endo_seg%22%2C%22precomputed://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-3/neuroglancer/mesh/endo_seg%22%5D%2C%22tab%22:%22source%22%2C%22segmentDefaultColor%22:%22#ff00ff%22%2C%22name%22:%22endo_seg%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%5B%22n5://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-3/jrc_hela-3.n5/labels/er_seg%22%2C%22precomputed://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-3/neuroglancer/mesh/er_seg%22%5D%2C%22tab%22:%22segments%22%2C%22segments%22:%5B%22134%22%2C%22159%22%5D%2C%22segmentQuery%22:%22134%22%2C%22segmentDefaultColor%22:%22#0000ff%22%2C%22name%22:%22er_seg%22%7D%2C%7B%22type%22:%22image%22%2C%22source%22:%7B%22url%22:%22precomputed://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-3/neuroglancer/em/fibsem-uint8.precomputed%22%2C%22transform%22:%7B%22matrix%22:%5B%5B1%2C0%2C0%2C0%5D%2C%5B0%2C-1%2C0%2C4000%5D%2C%5B0%2C0%2C1%2C0%5D%5D%2C%22outputDimensions%22:%7B%22x%22:%5B1e-9%2C%22m%22%5D%2C%22y%22:%5B1e-9%2C%22m%22%5D%2C%22z%22:%5B1e-9%2C%22m%22%5D%7D%7D%7D%2C%22tab%22:%22rendering%22%2C%22opacity%22:0.75%2C%22blend%22:%22additive%22%2C%22shader%22:%22#uicontrol%20invlerp%20normalized%28range=%5B55.08%2C%20240.72%5D%2C%20window=%5B0%2C%20255%5D%29%5Cn%20%20%20%20%20%20%20%20#uicontrol%20int%20invertColormap%20slider%28min=0%2C%20max=1%2C%20step=1%2C%20default=0%29%5Cn%20%20%20%20%20%20%20%20#uicontrol%20vec3%20color%20color%28default=%5C%22white%5C%22%29%5Cn%20%20%20%20%20%20%20%20float%20inverter%28float%20val%2C%20int%20invert%29%20%7Breturn%200.5%20+%20%28%282.0%20%2A%20%28-float%28invert%29%20+%200.5%29%29%20%2A%20%28val%20-%200.5%29%29%3B%7D%5Cn%20%20%20%20%20%20%20%20%20%20void%20main%28%29%20%7B%5Cn%20%20%20%20%20%20%20%20%20%20emitRGB%28color%20%2A%20inverter%28normalized%28%29%2C%20invertColormap%29%29%3B%5Cn%20%20%20%20%20%20%20%20%7D%22%2C%22name%22:%22fibsem-uint8%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%5B%22n5://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-3/jrc_hela-3.n5/labels/golgi_seg%22%2C%22precomputed://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-3/neuroglancer/mesh/golgi_seg%22%5D%2C%22tab%22:%22source%22%2C%22segmentDefaultColor%22:%22#00ffff%22%2C%22name%22:%22golgi_seg%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%5B%22n5://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-3/jrc_hela-3.n5/labels/mito_seg%22%2C%22precomputed://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-3/neuroglancer/mesh/mito_seg%22%5D%2C%22tab%22:%22source%22%2C%22segmentDefaultColor%22:%22#008000%22%2C%22name%22:%22mito_seg%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%5B%22n5://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-3/jrc_hela-3.n5/labels/nucleus_seg%22%2C%22precomputed://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-3/neuroglancer/mesh/nucleus_seg%22%5D%2C%22tab%22:%22source%22%2C%22segments%22:%5B%221%22%5D%2C%22segmentDefaultColor%22:%22#ff0000%22%2C%22name%22:%22nucleus_seg%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%5B%22n5://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-3/jrc_hela-3.n5/labels/pm_seg%22%2C%22precomputed://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-3/neuroglancer/mesh/pm_seg%22%5D%2C%22tab%22:%22source%22%2C%22segmentDefaultColor%22:%22#ffa500%22%2C%22name%22:%22pm_seg%22%7D%2C%7B%22type%22:%22segmentation%22%2C%22source%22:%5B%22n5://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-3/jrc_hela-3.n5/labels/vesicle_seg%22%2C%22precomputed://https://janelia-cosem-datasets.s3.amazonaws.com/jrc_hela-3/neuroglancer/mesh/vesicle_seg%22%5D%2C%22tab%22:%22source%22%2C%22segmentDefaultColor%22:%22#ff0000%22%2C%22name%22:%22vesicle_seg%22%7D%5D%2C%22selectedLayer%22:%7B%22visible%22:true%2C%22layer%22:%22er_seg%22%7D%2C%22crossSectionBackgroundColor%22:%22#000000%22%2C%22layout%22:%224panel%22%7D). Due to the fact that downsampling was performed on the data rather than the mesh, it can result in a somewhat more obvious transition between scales. Also, because this was performed chunkwise, decimation and smoothing was not possible without the resulting mesh having holes. This meant meshes were larger in memory and more blocky.

I haven't used my downsampling code yet for any published meshes, but it does seem to work well to my eye. [Here is a movie](https://drive.google.com/file/d/1Wv5RfrF-SF-387HGicSqG5Qi3x4t0zfh/view?usp=sharing) comparing my original method as described (top field of view) and my more recent code for decimating meshes (bottom field of view). Due to concerns about loading an entire mesh into memory, the newer method actually had a much lower resolution mesh as its lod 0 compared to the older method. And yet, it still looks good! Additionally there are many different parameters in [pyfqmr](https://github.com/Kramer84/pyfqmr-Fast-Quadric-Mesh-Reduction), that can be tuned to optimize either for speed or aesthetics. 

This topic has also led to similar discussions in my group, eg. whether meshes should be seen as useful 3D approximations to the data, or should strive to be as true to the underlying data as possible. I think I tend to be in the middle, where I want to keep things as accurate as possible, while also realizing the limitations imposed by latency and memory.

And I agree with you that 1) and 2) seem the more straightforward route, whereas 3) might be more involved. A lot can also depend on where you set the resolution slider in neuroglancer, because if you are zoomed out enough, low res meshes probably don't need to be very accurate/preserved compared to their higher res counterparts.

My repo allows you to provide meshes at a single scale or at all the scales you like, so you can try different approaches.

**Comment by davidackerman** [comment]
Yes, please feel free to use and integrate it! Glad it has proven useful and can contribute to your great pipelines.

**Comment by william-silversmith** [comment]
@davidackerman Would you mind if I asked you a question? I started to implement multi-res primarily as a way to get to sharded meshes and planned to add on true multi-res later so only a single LOD is currently represented. However, I meshed the Kasthuri et al S1 dataset (a few hundred gigavoxels) at 48x48x30 nm^3 resolution and saw odd displacements in my meshes. I checked the mean error between original and draco compressed meshes and also between the physical/stored model quantization and I think I've narrowed the issue to the draco compression (which I was doing at 16 bits). I didn't see this issue in smaller datasets, so I'm starting to think that I might need to start chunking the mesh? I tried bumping the number of bits to 24 to see if the mean error would reduce, but I still saw large displacements.

Have you experienced this problem before? How did you resolve it? Thanks so much for your help!

**Comment by davidackerman** [comment]
@william-silversmith I used to have some issues with offsets, eg. [here](https://github.com/google/neuroglancer/issues/266#issuecomment-739593224). This was because I wasn't doing vertex quantization prior to encoding with draco. I think this issue arises because without doing the quantization first, Draco meshes are shifted such that their lowest coordinates are aligned with the lower bounds of the corresponding bounding box. This is why I use [dividutils](https://github.com/davidackerman/dvidutils/tree/79a04fde902facc5e79098402b2f62b064ca612b) so that I can do the quantization before encoding to draco.

Other issues in terms of multires mesh loading can also arise if things aren't in the correct z-curve order.

And if you are using the multiresolution mesh format, then the only acceptable quantization bytes are 10 or 16, see [here](https://github.com/google/neuroglancer/blob/master/src/neuroglancer/datasource/precomputed/meshes.md#multi-resolution-mesh-manifest-file-format). In case that is an additional source of error.

I've also updated the multiresolution mesh code [here](https://github.com/janelia-cosem/multiresolution-mesh-creator) to make it more flexible and reliable.

**Comment by william-silversmith** [comment]
@davidackerman thank you for the info! I'm still working on this issue (been distracted by some other projects for the last week). I worked with the pyfqmr team and you can now easily install it via PyPI thanks to the maintainer Kristof's work: https://pypi.org/project/pyfqmr/

**Comment by william-silversmith** [comment]
Igneous can now produce sharded meshes using the multi-resolution container, but multi-res is still in progress.

**Comment by davidackerman** [comment]
Great thanks for the update! I have also been updating mesh generation on my end so things are faster and more efficient.
