### ISSUE TITLE
Client code as a separate package

### ISSUE THREAD

**Issue by chrisroat** [seung-lab/igneous#89]
I have one application that installs/import igneous just to get to the igneous.task_creation.create_transfer_tasks method.  A separate cluster, based on the igneous Docker image, is responsible for handling tasks from several applications and performing transfer/downsampling for viewers.

In your README.md, you mention being amenable to breaking out pieces of code as separate libraries.  Would the task handling code be a candidate for being a separate library?  

I'd like to shed the dependencies on libraries like kimimaro/tinybrain/zmesh.

**Comment by william-silversmith** [comment]
Hi Chris! That's an interesting suggestion. I've been considering revamping the task creation process (such as adding a CLI) for a while but there hasn't been much impetus to do so yet. Might I ask why the dependencies are a problem? I've been attempting to keep them updated such that installation isn't too difficult.

**Comment by chrisroat** [comment]
Hi!

One reason is that it pulls in all the downstream dependencies just to submit tasks to a queue. :)    The other reason is the licensing - an app simply submitting to a task queue is bound by the licensing of all theses dependencies it isn't using.

**Comment by william-silversmith** [comment]
Thinking about this some more there are some technical and licensing
hurdles that make this more difficult than it appears.

1. The task queuing code requires access to the definitions of the tasks it
is enqueuing. Breaking the code out separately would require maintaining a
set of dual function signatures that must remain synchronized. It might be
possible to put the import statements inside the functions/classes and
install dependencies on demand.
2. Igneous is GPL, which means that code derived from it must also be GPL,
so unless I were to write completely new code, it would be GPL as well
mechanically. There are quite a few contributors to Igneous that would have
to be tracked down and give their consent to change the license for the
derived code.
3. Igneous was originally GPL due to the integrated zmesh code that was
assigned GPL by its original author.

On the licensing front, I support the goals of the GPL. I don't use it for
all my libraries, but where it is used, I ask that it be respected as the
GPL is completely in sync with the spirit of open public benefit science.

If dependency installation is presenting difficulties, let me know what the
errors look like so we can find a good mitigation.

**Comment by chrisroat** [comment]
Thanks for your thoughts on this matter.

I don't have big troubles installing dependencies, beyond needing to build kimimaro from source (though maybe that has changed recently).  It's just awkward to depend on those additional libraries when the app is simply sending a message.

As far as licensing, I understand (and in many regards agree with) your sentiment.  I can likely work-around it by having a separate, small side application that takes an app's output and sends the message.

**Comment by william-silversmith** [comment]
Thanks Chris! Can you let me know what OS and Python version you're using?
I was hoping to have Kimimaro binaries built for all the common deployments.

**Comment by chrisroat** [comment]
I've been using Ubuntu 18.04/20.04 and python 3.7/3.8.  I setup our Dockerfile many months ago.  Several packages we used needed to be source-built at the time, so I added a build stage and included kimimaro.   It's totally conceivable that now I could drop kimimaro from the build - I'll try it the next time I update.  (Not a big pain point, since its just one of several pkgs.)

Dependency management is fun!  (not!)

Happy to close this.  Thanks for the discussion.
